# Generated by Django 4.1.1 on 2022-10-06 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrohoraextra", "0002_horaextra_funcionario"),
    ]

    operations = [
        migrations.AddField(
            model_name="horaextra",
            name="horas",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
