# Generated by Django 4.1.1 on 2022-10-03 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("funcionarios", "0003_alter_funcionario_user"),
        ("documentos", "0002_documento_dono"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documento",
            name="dono",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="funcionarios.funcionario",
                verbose_name="Proprietário do Documento",
            ),
            preserve_default=False,
        ),
    ]
