# Generated by Django 4.1.1 on 2022-10-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0003_alter_documento_dono"),
    ]

    operations = [
        migrations.AddField(
            model_name="documento",
            name="arquivo",
            field=models.FileField(default=1, upload_to="documentos"),
            preserve_default=False,
        ),
    ]
